services:
  app:
    container_name: app-two
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    networks:
      - initiatives
  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    command: http --domain=$MY_DOMAIN app:4000
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - initiatives
volumes:
  rubygems:
  project-two-data:

networks:
  initiatives:
    external: true
