version: '3'

services:
  app:
    container_name: app-two
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    networks:
      - initiatives
volumes:
  rubygems:
  project-two-data:

networks:
  initiatives:
    external: true
